//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Citation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本软件为免费软件，受《计算机软件保护条例》及其它国家或地区同等权利保护，未经许可，不得用于商业用途。任何侵权行为都将受到法律允许的最大程度的追究。.
        /// </summary>
        public static string AboutPage_Alert {
            get {
                return ResourceManager.GetString("AboutPage_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式：.
        /// </summary>
        public static string AboutPage_Contact {
            get {
                return ResourceManager.GetString("AboutPage_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯地址：.
        /// </summary>
        public static string AboutPage_Contact_Address {
            get {
                return ResourceManager.GetString("AboutPage_Contact_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 山东省泰安市泰山区泮河大街7号 山东农业大学泮河校区 271017 农学院 Arabidopsis.
        /// </summary>
        public static string AboutPage_Contact_AddressDetail {
            get {
                return ResourceManager.GetString("AboutPage_Contact_AddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 Arabidopsis. 保留所有权利。.
        /// </summary>
        public static string AboutPage_Contact_Copyright {
            get {
                return ResourceManager.GetString("AboutPage_Contact_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱: arab@methodbox.top.
        /// </summary>
        public static string AboutPage_Contact_Emali {
            get {
                return ResourceManager.GetString("AboutPage_Contact_Emali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件信息.
        /// </summary>
        public static string AboutPage_Contact_SoftwareInfo {
            get {
                return ResourceManager.GetString("AboutPage_Contact_SoftwareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本: v4（内部版本 Dev_tfo1100a+）.
        /// </summary>
        public static string AboutPage_Contact_Version {
            get {
                return ResourceManager.GetString("AboutPage_Contact_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发团队.
        /// </summary>
        public static string AboutPage_DevelopmentGroup {
            get {
                return ResourceManager.GetString("AboutPage_DevelopmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发组织：Project MethodBox.
        /// </summary>
        public static string AboutPage_DevelopmentOrganize {
            get {
                return ResourceManager.GetString("AboutPage_DevelopmentOrganize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发人员：Arabidopsis.
        /// </summary>
        public static string AboutPage_MainDeveloper {
            get {
                return ResourceManager.GetString("AboutPage_MainDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科研一站式管理工具.
        /// </summary>
        public static string AboutPage_ShortDescription {
            get {
                return ResourceManager.GetString("AboutPage_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致谢名单.
        /// </summary>
        public static string AboutPage_Thanks {
            get {
                return ResourceManager.GetString("AboutPage_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒标题.
        /// </summary>
        public static string AddAlertPage_AlertCapital {
            get {
                return ResourceManager.GetString("AddAlertPage_AlertCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒详情.
        /// </summary>
        public static string AddAlertPage_AlertDescription {
            get {
                return ResourceManager.GetString("AddAlertPage_AlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒时间.
        /// </summary>
        public static string AddAlertPage_AlertTime {
            get {
                return ResourceManager.GetString("AddAlertPage_AlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加提醒.
        /// </summary>
        public static string AddAlertPage_PageCapital {
            get {
                return ResourceManager.GetString("AddAlertPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产公司.
        /// </summary>
        public static string AddInstrument_InstrumentCompany {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器描述.
        /// </summary>
        public static string AddInstrument_InstrumentDescription {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负责人.
        /// </summary>
        public static string AddInstrument_InstrumentDirector {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 型号.
        /// </summary>
        public static string AddInstrument_InstrumentModel {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器名称.
        /// </summary>
        public static string AddInstrument_InstrumentName {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        public static string AddInstrument_InstrumentPrice {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买日期.
        /// </summary>
        public static string AddInstrument_InstrumentPurchaseDate {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器编号.
        /// </summary>
        public static string AddInstrument_InstrumentSeries {
            get {
                return ResourceManager.GetString("AddInstrument_InstrumentSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加仪器.
        /// </summary>
        public static string AddInstrument_PageCapital {
            get {
                return ResourceManager.GetString("AddInstrument_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居中.
        /// </summary>
        public static string AddNotePage_Aglin_Center {
            get {
                return ResourceManager.GetString("AddNotePage_Aglin_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左对齐.
        /// </summary>
        public static string AddNotePage_Aglin_Left {
            get {
                return ResourceManager.GetString("AddNotePage_Aglin_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右对齐.
        /// </summary>
        public static string AddNotePage_Aglin_Right {
            get {
                return ResourceManager.GetString("AddNotePage_Aglin_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string AddNotePage_Color {
            get {
                return ResourceManager.GetString("AddNotePage_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加粗.
        /// </summary>
        public static string AddNotePage_Font_Bold {
            get {
                return ResourceManager.GetString("AddNotePage_Font_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斜体.
        /// </summary>
        public static string AddNotePage_Font_Italic {
            get {
                return ResourceManager.GetString("AddNotePage_Font_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下划线.
        /// </summary>
        public static string AddNotePage_Font_Underline {
            get {
                return ResourceManager.GetString("AddNotePage_Font_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称：.
        /// </summary>
        public static string AddNotePage_NoteName {
            get {
                return ResourceManager.GetString("AddNotePage_NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑便签.
        /// </summary>
        public static string AddNotePage_PageCapital {
            get {
                return ResourceManager.GetString("AddNotePage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束提醒.
        /// </summary>
        public static string AddTaskPage_EndAlert {
            get {
                return ResourceManager.GetString("AddTaskPage_EndAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加任务.
        /// </summary>
        public static string AddTaskPage_PageCapital {
            get {
                return ResourceManager.GetString("AddTaskPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始提醒.
        /// </summary>
        public static string AddTaskPage_StartAlert {
            get {
                return ResourceManager.GetString("AddTaskPage_StartAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务描述.
        /// </summary>
        public static string AddTaskPage_TaskDescription {
            get {
                return ResourceManager.GetString("AddTaskPage_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string AddTaskPage_TaskEndTime {
            get {
                return ResourceManager.GetString("AddTaskPage_TaskEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务名称.
        /// </summary>
        public static string AddTaskPage_TaskName {
            get {
                return ResourceManager.GetString("AddTaskPage_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string AddTaskPage_TaskStartTime {
            get {
                return ResourceManager.GetString("AddTaskPage_TaskStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒通知.
        /// </summary>
        public static string AlertWindow_PageCapital {
            get {
                return ResourceManager.GetString("AlertWindow_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权访问.
        /// </summary>
        public static string AuthorizationWindow_Authorize {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认授权.
        /// </summary>
        public static string AuthorizationWindow_Confirm {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation Security© By Arabidopsis 2025. All right reserved..
        /// </summary>
        public static string AuthorizationWindow_Copyright {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （危险操作）.
        /// </summary>
        public static string AuthorizationWindow_Dangerous {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation Security©  已禁用.
        /// </summary>
        public static string AuthorizationWindow_Disabled {
            get {
                return ResourceManager.GetString("AuthorizationWindow_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在演示版和试用版中，该功能会被禁用，以保障正式版用户权益不受损害.
        /// </summary>
        public static string AuthorizationWindow_DisabledAlert {
            get {
                return ResourceManager.GetString("AuthorizationWindow_DisabledAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过期时间.
        /// </summary>
        public static string AuthorizationWindow_ExpireTime {
            get {
                return ResourceManager.GetString("AuthorizationWindow_ExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目密码（本项必填，用于验证您的身份）.
        /// </summary>
        public static string AuthorizationWindow_InputPassword {
            get {
                return ResourceManager.GetString("AuthorizationWindow_InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入本机序列号 (例如: 0A06A2-123733-5AC45C).
        /// </summary>
        public static string AuthorizationWindow_InputSerial {
            get {
                return ResourceManager.GetString("AuthorizationWindow_InputSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本机序列号列表.
        /// </summary>
        public static string AuthorizationWindow_SerialList {
            get {
                return ResourceManager.GetString("AuthorizationWindow_SerialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择过期时间.
        /// </summary>
        public static string AuthorizationWindow_WExpireTime {
            get {
                return ResourceManager.GetString("AuthorizationWindow_WExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入文章链接....
        /// </summary>
        public static string CitationPage_InputLink {
            get {
                return ResourceManager.GetString("CitationPage_InputLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新的引用.
        /// </summary>
        public static string CitationPage_PageCapital {
            get {
                return ResourceManager.GetString("CitationPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摘要.
        /// </summary>
        public static string DetailPage_Abstract {
            get {
                return ResourceManager.GetString("DetailPage_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string DetailPage_ArticleCapital {
            get {
                return ResourceManager.GetString("DetailPage_ArticleCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期刊名称.
        /// </summary>
        public static string DetailPage_JournalName {
            get {
                return ResourceManager.GetString("DetailPage_JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页码.
        /// </summary>
        public static string DetailPage_Page {
            get {
                return ResourceManager.GetString("DetailPage_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引用详细信息.
        /// </summary>
        public static string DetailPage_PageCapital {
            get {
                return ResourceManager.GetString("DetailPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发表日期.
        /// </summary>
        public static string DetailPage_PublicationDate {
            get {
                return ResourceManager.GetString("DetailPage_PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件夹（子课题）.
        /// </summary>
        public static string DetailPage_SaveFolder {
            get {
                return ResourceManager.GetString("DetailPage_SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期号.
        /// </summary>
        public static string DetailPage_Volume {
            get {
                return ResourceManager.GetString("DetailPage_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空筛选.
        /// </summary>
        public static string ExportPage_ClearFilter {
            get {
                return ResourceManager.GetString("ExportPage_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空所有筛选条件.
        /// </summary>
        public static string ExportPage_ClearFilterToolTip {
            get {
                return ResourceManager.GetString("ExportPage_ClearFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出引用.
        /// </summary>
        public static string ExportPage_ExportCite {
            get {
                return ResourceManager.GetString("ExportPage_ExportCite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筛选条件：.
        /// </summary>
        public static string ExportPage_Filter {
            get {
                return ResourceManager.GetString("ExportPage_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按课题筛选.
        /// </summary>
        public static string ExportPage_Filter_ByClass {
            get {
                return ResourceManager.GetString("ExportPage_Filter_ByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按期刊筛选.
        /// </summary>
        public static string ExportPage_Filter_ByJournal {
            get {
                return ResourceManager.GetString("ExportPage_Filter_ByJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实际大小.
        /// </summary>
        public static string FieldExperimentPage_100Percent {
            get {
                return ResourceManager.GetString("FieldExperimentPage_100Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 适应.
        /// </summary>
        public static string FieldExperimentPage_Adapt {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Adapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加标识牌.
        /// </summary>
        public static string FieldExperimentPage_AddSign {
            get {
                return ResourceManager.GetString("FieldExperimentPage_AddSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI辅助设计.
        /// </summary>
        public static string FieldExperimentPage_AIDesign {
            get {
                return ResourceManager.GetString("FieldExperimentPage_AIDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放：100%.
        /// </summary>
        public static string FieldExperimentPage_DefaultScale {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DefaultScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具：平移.
        /// </summary>
        public static string FieldExperimentPage_DefaultTool {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DefaultTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设计类型.
        /// </summary>
        public static string FieldExperimentPage_DesignType {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DesignType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绘制区组.
        /// </summary>
        public static string FieldExperimentPage_DrawArea {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DrawArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绘制实验小区.
        /// </summary>
        public static string FieldExperimentPage_DrawExpr {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DrawExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绘制田间小区.
        /// </summary>
        public static string FieldExperimentPage_DrawField {
            get {
                return ResourceManager.GetString("FieldExperimentPage_DrawField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实验描述.
        /// </summary>
        public static string FieldExperimentPage_ExperimentDesc {
            get {
                return ResourceManager.GetString("FieldExperimentPage_ExperimentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实验名称.
        /// </summary>
        public static string FieldExperimentPage_ExperimentName {
            get {
                return ResourceManager.GetString("FieldExperimentPage_ExperimentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实验属性.
        /// </summary>
        public static string FieldExperimentPage_ExperimentProp {
            get {
                return ResourceManager.GetString("FieldExperimentPage_ExperimentProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工具.
        /// </summary>
        public static string FieldExperimentPage_Left_Choose {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Left_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        public static string FieldExperimentPage_Left_ToolTip {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Left_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载实验.
        /// </summary>
        public static string FieldExperimentPage_LoadExpr {
            get {
                return ResourceManager.GetString("FieldExperimentPage_LoadExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放大.
        /// </summary>
        public static string FieldExperimentPage_Magnify {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Magnify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建实验.
        /// </summary>
        public static string FieldExperimentPage_NewExpr {
            get {
                return ResourceManager.GetString("FieldExperimentPage_NewExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理库.
        /// </summary>
        public static string FieldExperimentPage_Processes {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小.
        /// </summary>
        public static string FieldExperimentPage_Reduce {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存实验.
        /// </summary>
        public static string FieldExperimentPage_SaveExpr {
            get {
                return ResourceManager.GetString("FieldExperimentPage_SaveExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放工具.
        /// </summary>
        public static string FieldExperimentPage_Scale {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平移工具.
        /// </summary>
        public static string FieldExperimentPage_Translation {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机区组设计.
        /// </summary>
        public static string FieldExperimentPage_Type_CRD {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Type_CRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拉丁方设计.
        /// </summary>
        public static string FieldExperimentPage_Type_LSD {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Type_LSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裂区实验设计.
        /// </summary>
        public static string FieldExperimentPage_Type_ND {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Type_ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全随机区组设计.
        /// </summary>
        public static string FieldExperimentPage_Type_RCBD {
            get {
                return ResourceManager.GetString("FieldExperimentPage_Type_RCBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论文自动查找.
        /// </summary>
        public static string FindNLPage_PageCapital {
            get {
                return ResourceManager.GetString("FindNLPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到 0 篇相似文献.
        /// </summary>
        public static string FindSimilarPage_DefaultFind {
            get {
                return ResourceManager.GetString("FindSimilarPage_DefaultFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详情页.
        /// </summary>
        public static string FindSimilarPage_DetailPage {
            get {
                return ResourceManager.GetString("FindSimilarPage_DetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载PDF.
        /// </summary>
        public static string FindSimilarPage_DownloadPDF {
            get {
                return ResourceManager.GetString("FindSimilarPage_DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找相似文献.
        /// </summary>
        public static string FindSimilarPage_FindSimilar {
            get {
                return ResourceManager.GetString("FindSimilarPage_FindSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无结果，尝试添加引用其它文献.
        /// </summary>
        public static string FindSimilarPage_NoResult {
            get {
                return ResourceManager.GetString("FindSimilarPage_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI相似文献查找.
        /// </summary>
        public static string FindSimilarPage_PageCapital {
            get {
                return ResourceManager.GetString("FindSimilarPage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文献标题、DOI或关键词.
        /// </summary>
        public static string FindSimilarPage_Prompt {
            get {
                return ResourceManager.GetString("FindSimilarPage_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看详情.
        /// </summary>
        public static string FindSimilarPage_RevealDetail {
            get {
                return ResourceManager.GetString("FindSimilarPage_RevealDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文献.
        /// </summary>
        public static string FindSimilarPage_SaveArticle {
            get {
                return ResourceManager.GetString("FindSimilarPage_SaveArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果导入时，软件提示文件损坏，那么是ris格式文件已经损坏，请您重新下载构建ris文件，之后导入。.
        /// </summary>
        public static string ImportFailurePage_Alert1 {
            get {
                return ResourceManager.GetString("ImportFailurePage_Alert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果您未连接互联网，将会导致全部文献导入失败，请确保您已经连接到互联网。.
        /// </summary>
        public static string ImportFailurePage_Alert2 {
            get {
                return ResourceManager.GetString("ImportFailurePage_Alert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果导入速度缓慢，且部分或全部不成功，请暂时关闭电脑上运行的vpn或刷新dns缓存后重试。.
        /// </summary>
        public static string ImportFailurePage_Alert3 {
            get {
                return ResourceManager.GetString("ImportFailurePage_Alert3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果小部分最近的文献导入不成功，说明该文献还没有被正式同步，请您过几天之后重试，或者在单个导入界面中，手动输入论文相关信息。.
        /// </summary>
        public static string ImportFailurePage_Alert4 {
            get {
                return ResourceManager.GetString("ImportFailurePage_Alert4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果遇到其他问题，请加入用户群或者发送邮件反馈。.
        /// </summary>
        public static string ImportFailurePage_Alert5 {
            get {
                return ResourceManager.GetString("ImportFailurePage_Alert5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感谢您使用 Arabidopsis Citation！我们将持续改进产品体验。.
        /// </summary>
        public static string ImportFailurePage_Buttom {
            get {
                return ResourceManager.GetString("ImportFailurePage_Buttom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为什么会出现导入失败？.
        /// </summary>
        public static string ImportFailurePage_PageCapital {
            get {
                return ResourceManager.GetString("ImportFailurePage_PageCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开源许可协议.
        /// </summary>
        public static string LicenseWindow_Agreement {
            get {
                return ResourceManager.GetString("LicenseWindow_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请仔细阅读以下许可协议内容。要继续使用本软件，您需要接受此协议的所有条款。.
        /// </summary>
        public static string LicenseWindow_Prompt {
            get {
                return ResourceManager.GetString("LicenseWindow_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目名称.
        /// </summary>
        public static string Main_Bottom_ProjectName {
            get {
                return ResourceManager.GetString("Main_Bottom_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 助手.
        /// </summary>
        public static string Main_Top_Assistant {
            get {
                return ResourceManager.GetString("Main_Top_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找相似论文.
        /// </summary>
        public static string Main_Top_Assistant_FindSimilar {
            get {
                return ResourceManager.GetString("Main_Top_Assistant_FindSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动查找文献.
        /// </summary>
        public static string Main_Top_Assistant_NaturalFind {
            get {
                return ResourceManager.GetString("Main_Top_Assistant_NaturalFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引用.
        /// </summary>
        public static string Main_Top_Cite {
            get {
                return ResourceManager.GetString("Main_Top_Cite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加引用.
        /// </summary>
        public static string Main_Top_Cite_AddCite {
            get {
                return ResourceManager.GetString("Main_Top_Cite_AddCite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出引用.
        /// </summary>
        public static string Main_Top_Cite_ExportCite {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ExportCite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至交换文件.
        /// </summary>
        public static string Main_Top_Cite_ExportCite_ToExchangeFile {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ExportCite_ToExchangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至格式文件.
        /// </summary>
        public static string Main_Top_Cite_ExportCite_ToFormatFile {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ExportCite_ToFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看失败原因.
        /// </summary>
        public static string Main_Top_Cite_Failure {
            get {
                return ResourceManager.GetString("Main_Top_Cite_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入引用.
        /// </summary>
        public static string Main_Top_Cite_ImportCite {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ImportCite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看引用.
        /// </summary>
        public static string Main_Top_Cite_ViewCite {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ViewCite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看时间线.
        /// </summary>
        public static string Main_Top_Cite_ViewStoryLine {
            get {
                return ResourceManager.GetString("Main_Top_Cite_ViewStoryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实验.
        /// </summary>
        public static string Main_Top_Experiment {
            get {
                return ResourceManager.GetString("Main_Top_Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大田实验.
        /// </summary>
        public static string Main_Top_Experiment_Field {
            get {
                return ResourceManager.GetString("Main_Top_Experiment_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其它.
        /// </summary>
        public static string Main_Top_Others {
            get {
                return ResourceManager.GetString("Main_Top_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Main_Top_Others_About {
            get {
                return ResourceManager.GetString("Main_Top_Others_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本机序列号.
        /// </summary>
        public static string Main_Top_Others_LocalLicense {
            get {
                return ResourceManager.GetString("Main_Top_Others_LocalLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件设置.
        /// </summary>
        public static string Main_Top_Others_SoftwareSettings {
            get {
                return ResourceManager.GetString("Main_Top_Others_SoftwareSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目.
        /// </summary>
        public static string Main_Top_Project {
            get {
                return ResourceManager.GetString("Main_Top_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份.
        /// </summary>
        public static string Main_Top_Project_Backup {
            get {
                return ResourceManager.GetString("Main_Top_Project_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Main_Top_Project_Close {
            get {
                return ResourceManager.GetString("Main_Top_Project_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Main_Top_Project_Exit {
            get {
                return ResourceManager.GetString("Main_Top_Project_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Main_Top_Project_New {
            get {
                return ResourceManager.GetString("Main_Top_Project_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Main_Top_Project_Open {
            get {
                return ResourceManager.GetString("Main_Top_Project_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目设置.
        /// </summary>
        public static string Main_Top_Project_Settings {
            get {
                return ResourceManager.GetString("Main_Top_Project_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享授权.
        /// </summary>
        public static string Main_Top_Project_ShareAuth {
            get {
                return ResourceManager.GetString("Main_Top_Project_ShareAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录.
        /// </summary>
        public static string Main_Top_Record {
            get {
                return ResourceManager.GetString("Main_Top_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备.
        /// </summary>
        public static string Main_Top_Record_Device {
            get {
                return ResourceManager.GetString("Main_Top_Record_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加仪器.
        /// </summary>
        public static string Main_Top_Record_Device_AddInstrument {
            get {
                return ResourceManager.GetString("Main_Top_Record_Device_AddInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理仪器.
        /// </summary>
        public static string Main_Top_Record_Device_ManageInstrument {
            get {
                return ResourceManager.GetString("Main_Top_Record_Device_ManageInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 便签.
        /// </summary>
        public static string Main_Top_Record_Note {
            get {
                return ResourceManager.GetString("Main_Top_Record_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速新建.
        /// </summary>
        public static string Main_Top_Record_Note_AddNote {
            get {
                return ResourceManager.GetString("Main_Top_Record_Note_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看便签.
        /// </summary>
        public static string Main_Top_Record_Note_ViewNote {
            get {
                return ResourceManager.GetString("Main_Top_Record_Note_ViewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务.
        /// </summary>
        public static string Main_Top_Task {
            get {
                return ResourceManager.GetString("Main_Top_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加提醒.
        /// </summary>
        public static string Main_Top_Task_AddAlert {
            get {
                return ResourceManager.GetString("Main_Top_Task_AddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规划任务.
        /// </summary>
        public static string Main_Top_Task_AddTask {
            get {
                return ResourceManager.GetString("Main_Top_Task_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置提醒.
        /// </summary>
        public static string Main_Top_Task_SetAlert {
            get {
                return ResourceManager.GetString("Main_Top_Task_SetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看任务.
        /// </summary>
        public static string Main_Top_Task_ViewTask {
            get {
                return ResourceManager.GetString("Main_Top_Task_ViewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请描述您希望查找的论文包含的元素.
        /// </summary>
        public static string NLFindPage_InputLink {
            get {
                return ResourceManager.GetString("NLFindPage_InputLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Public_Add {
            get {
                return ResourceManager.GetString("Public_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同意.
        /// </summary>
        public static string Public_Agree {
            get {
                return ResourceManager.GetString("Public_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Public_Cancel {
            get {
                return ResourceManager.GetString("Public_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Public_Clear {
            get {
                return ResourceManager.GetString("Public_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Public_Close {
            get {
                return ResourceManager.GetString("Public_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Public_Confirm {
            get {
                return ResourceManager.GetString("Public_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Public_Delete {
            get {
                return ResourceManager.GetString("Public_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝.
        /// </summary>
        public static string Public_Deny {
            get {
                return ResourceManager.GetString("Public_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Public_Edit {
            get {
                return ResourceManager.GetString("Public_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载.
        /// </summary>
        public static string Public_Load {
            get {
                return ResourceManager.GetString("Public_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动.
        /// </summary>
        public static string Public_Manual {
            get {
                return ResourceManager.GetString("Public_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Public_New {
            get {
                return ResourceManager.GetString("Public_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string Public_Reveal {
            get {
                return ResourceManager.GetString("Public_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Public_Save {
            get {
                return ResourceManager.GetString("Public_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文献引用时使用的格式化样式，更改将在下次引用时生效。.
        /// </summary>
        public static string SettingPage_FormatInstruction {
            get {
                return ResourceManager.GetString("SettingPage_FormatInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式化样式.
        /// </summary>
        public static string SettingPage_FormatStyle {
            get {
                return ResourceManager.GetString("SettingPage_FormatStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目格式化选项.
        /// </summary>
        public static string SettingPage_Formatter {
            get {
                return ResourceManager.GetString("SettingPage_Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多设置选项将在后续版本中提供....
        /// </summary>
        public static string SettingPage_OtherInstruction {
            get {
                return ResourceManager.GetString("SettingPage_OtherInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他设置.
        /// </summary>
        public static string SettingPage_OtherSettings {
            get {
                return ResourceManager.GetString("SettingPage_OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目 .
        /// </summary>
        public static string SettingPage_PageCapitalLeft {
            get {
                return ResourceManager.GetString("SettingPage_PageCapitalLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置项.
        /// </summary>
        public static string SettingPage_PageCapitalRight {
            get {
                return ResourceManager.GetString("SettingPage_PageCapitalRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请配置您的 Deepseek APIKey。.
        /// </summary>
        public static string SoftwareSettingPage_AIInstruction {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_AIInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI助手设置.
        /// </summary>
        public static string SoftwareSettingPage_AssistantSetting {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_AssistantSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库设置.
        /// </summary>
        public static string SoftwareSettingPage_Database {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设置项目数据库的密码。.
        /// </summary>
        public static string SoftwareSettingPage_DatabaseInstruction {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_DatabaseInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库密码.
        /// </summary>
        public static string SoftwareSettingPage_DatabasePassword {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_DatabasePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的 DeepSeek APIKey：.
        /// </summary>
        public static string SoftwareSettingPage_DeepseekAPI {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_DeepseekAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用安全防护：.
        /// </summary>
        public static string SoftwareSettingPage_EnableSecurity {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_EnableSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多设置将在后续版本中提供....
        /// </summary>
        public static string SoftwareSettingPage_OtherInstrument {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_OtherInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其它设置.
        /// </summary>
        public static string SoftwareSettingPage_OtherSettings {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件.
        /// </summary>
        public static string SoftwareSettingPage_PageCapitalLeft {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_PageCapitalLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置项.
        /// </summary>
        public static string SoftwareSettingPage_PageCapitalRight {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_PageCapitalRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以启用安全防护并选择具体的防护版本。.
        /// </summary>
        public static string SoftwareSettingPage_SecurityAlert {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_SecurityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全防护算法.
        /// </summary>
        public static string SoftwareSettingPage_SecurityAlgorithm {
            get {
                return ResourceManager.GetString("SoftwareSettingPage_SecurityAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒标题.
        /// </summary>
        public static string ViewAlertPage_AlertCaptial {
            get {
                return ResourceManager.GetString("ViewAlertPage_AlertCaptial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除提醒.
        /// </summary>
        public static string ViewAlertPage_DeleteAlert {
            get {
                return ResourceManager.GetString("ViewAlertPage_DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string ViewAlertPage_Description {
            get {
                return ResourceManager.GetString("ViewAlertPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑提醒.
        /// </summary>
        public static string ViewAlertPage_EditAlert {
            get {
                return ResourceManager.GetString("ViewAlertPage_EditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看提醒.
        /// </summary>
        public static string ViewAlertPage_PageTitle {
            get {
                return ResourceManager.GetString("ViewAlertPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        public static string ViewAlertPage_Time {
            get {
                return ResourceManager.GetString("ViewAlertPage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除仪器.
        /// </summary>
        public static string ViewInstrumentPage_DeleteInstrument {
            get {
                return ResourceManager.GetString("ViewInstrumentPage_DeleteInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑仪器.
        /// </summary>
        public static string ViewInstrumentPage_EditInstrument {
            get {
                return ResourceManager.GetString("ViewInstrumentPage_EditInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器管理.
        /// </summary>
        public static string ViewInstrumentPage_PageTitle {
            get {
                return ResourceManager.GetString("ViewInstrumentPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除便签.
        /// </summary>
        public static string ViewNotePage_DeleteNote {
            get {
                return ResourceManager.GetString("ViewNotePage_DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑便签.
        /// </summary>
        public static string ViewNotePage_EditNote {
            get {
                return ResourceManager.GetString("ViewNotePage_EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 便签管理.
        /// </summary>
        public static string ViewNotePage_PageTitle {
            get {
                return ResourceManager.GetString("ViewNotePage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摘要.
        /// </summary>
        public static string ViewReferencePage_Abstract {
            get {
                return ResourceManager.GetString("ViewReferencePage_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尚未选择输出类型.
        /// </summary>
        public static string ViewReferencePage_AlertType {
            get {
                return ResourceManager.GetString("ViewReferencePage_AlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string ViewReferencePage_Author {
            get {
                return ResourceManager.GetString("ViewReferencePage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string ViewReferencePage_Capital {
            get {
                return ResourceManager.GetString("ViewReferencePage_Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制引用.
        /// </summary>
        public static string ViewReferencePage_CopyRef {
            get {
                return ResourceManager.GetString("ViewReferencePage_CopyRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引用格式.
        /// </summary>
        public static string ViewReferencePage_Formatter {
            get {
                return ResourceManager.GetString("ViewReferencePage_Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期号.
        /// </summary>
        public static string ViewReferencePage_Issue {
            get {
                return ResourceManager.GetString("ViewReferencePage_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期刊名称.
        /// </summary>
        public static string ViewReferencePage_JournalName {
            get {
                return ResourceManager.GetString("ViewReferencePage_JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页码.
        /// </summary>
        public static string ViewReferencePage_Page {
            get {
                return ResourceManager.GetString("ViewReferencePage_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文献详细信息.
        /// </summary>
        public static string ViewReferencePage_PageTitle {
            get {
                return ResourceManager.GetString("ViewReferencePage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发表日期.
        /// </summary>
        public static string ViewReferencePage_PublicationDate {
            get {
                return ResourceManager.GetString("ViewReferencePage_PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束提醒.
        /// </summary>
        public static string ViewTaskPage_EndAlert {
            get {
                return ResourceManager.GetString("ViewTaskPage_EndAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放.
        /// </summary>
        public static string ViewTaskPage_Scale {
            get {
                return ResourceManager.GetString("ViewTaskPage_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始提醒.
        /// </summary>
        public static string ViewTaskPage_StartAlert {
            get {
                return ResourceManager.GetString("ViewTaskPage_StartAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Arabidopsis 2025, All rights reserved..
        /// </summary>
        public static string WelcomePage_Copyright {
            get {
                return ResourceManager.GetString("WelcomePage_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建项目.
        /// </summary>
        public static string WelcomePage_CreateProject {
            get {
                return ResourceManager.GetString("WelcomePage_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation and beyond..
        /// </summary>
        public static string WelcomePage_Motto {
            get {
                return ResourceManager.GetString("WelcomePage_Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开项目.
        /// </summary>
        public static string WelcomePage_OpenProject {
            get {
                return ResourceManager.GetString("WelcomePage_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎使用 Citation ！.
        /// </summary>
        public static string WelcomePage_WelcomeText {
            get {
                return ResourceManager.GetString("WelcomePage_WelcomeText", resourceCulture);
            }
        }
    }
}
